name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Компиляция
      run: g++ add.cpp -o add
      
    - name: Проверка компиляции
      run: |
        if [ -f add ]; then
          echo "✅ Компиляция успешна"
        else
          echo "❌ Ошибка компиляции"
          exit 1
        fi
